type Props = {
  sender: string;
  receiver: string;
  amount: string;
  paymentMethod: string;
  description: string;
  receiptNumber: string;

  transactionId: string;
  sessionId: string;
  transactionDate: string;
  transactionTime: string;
  status: string;
};

export default function OPayReceipt({
  sender,
  receiver,
  amount,
  paymentMethod,
  description,
  receiptNumber,
}: Props) {
  return (
    <div className="w-[430px] bg-white rounded-3xl shadow-2xl overflow-hidden border border-gray-200">
      {/* Header */}
      <div className="bg-green-600 text-white text-center p-8">
        <h1 className="text-4xl font-bold">OPay</h1>
        <p className="mt-2">Transaction Successful</p>

        <h2 className="text-5xl font-bold mt-6">
          ₦{Number(amount).toLocaleString()}
        </h2>
      </div>

      {/* Body */}
      <div className="p-8 space-y-4">
        <Item label="Sender" value={sender} />
        <Item label="Receiver" value={receiver} />
        <Item label="Payment Method" value={paymentMethod} />
        <Item label="Description" value={description} />
        <Item label="Receipt Number" value={receiptNumber} />
        <Item
          label="Reference"
          value={`REF${Math.floor(Math.random() * 1000000000)}`}
        />
        <Item
          label="Session ID"
          value={Math.random().toString().substring(2, 14)}
        />
        <Item
          label="Date"
          value={new Date().toLocaleString()}
        />
        <Item label="Status" value="Successful" />
      </div>

      {/* Footer */}
      <div className="bg-gray-100 text-center py-5 text-gray-500">
        Generated by Receiptly
      </div>
    </div>
  );
}

function Item({
  label,
  value,
}: {
  label: string;
  value: string;
}) {
  return (
    <div className="flex justify-between border-b pb-3">
      <span className="text-gray-500">{label}</span>

      <span className="font-semibold text-right max-w-[220px] break-words">
        {value}
      </span>
    </div>
  );
}