import jsPDF from "jspdf";

export function generateReceiptPdf(
  receiptNumber: string,
  sender: string,
  receiver: string,
  amount: string,
  paymentMethod: string,
  description: string,
  bank: string
) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

const center = pageWidth / 2;

const reference =
  "REF" +
  Math.floor(
    1000000000 + Math.random() * 9000000000
  );

const session =
  Math.floor(
    100000000000000000 + Math.random() * 900000000000000000
  ).toString();

const now = new Date();

const date = now.toLocaleDateString();

const time = now.toLocaleTimeString();

  let primaryColor = [0, 180, 0];
  let bankName = "OPay";

  switch (bank) {
    case "PalmPay":
      primaryColor = [110, 0, 255];
      bankName = "PalmPay";
      break;

    case "Moniepoint":
      primaryColor = [0, 60, 255];
      bankName = "Moniepoint";
      break;

    case "GTBank":
      primaryColor = [255, 102, 0];
      bankName = "GTBank";
      break;

    case "Access Bank":
      primaryColor = [0, 40, 130];
      bankName = "Access Bank";
      break;

    default:
      primaryColor = [0, 180, 0];
      bankName = "OPay";
  }

  // Header
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(0, 0, 210, 35, "F");

  doc.setFontSize(24);
  doc.setTextColor(255,255,255);
  doc.text(bankName,20,22);

  doc.setFontSize(12);
  doc.text("Transaction Receipt",20,30);

  // Amount
  doc.setTextColor(0,0,0);

  doc.setFontSize(18);
  doc.text("SUCCESSFUL",20,50);
  doc.setFontSize(12);

doc.setTextColor(80);

doc.text(
  "Your transaction has been completed successfully.",
  center,
  58,
  {
    align: "center",
  }
);

  doc.setFontSize(30);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text(`₦${Number(amount).toLocaleString()}`,20,68);

  doc.setTextColor(0,0,0);

  doc.setDrawColor(220);
  doc.line(20,78,190,78);

  let y = 92;

  function row(title:string,value:string){
      doc.setFont("helvetica","bold");
      doc.text(title,20,y);

      doc.setFont("helvetica","normal");
      doc.text(value,90,y);

      y+=12;
  }

  row("Sender",sender);
  row("Receiver",receiver);
  row("Payment Method",paymentMethod);
  row("Description",description);
  row("Receipt No.",receiptNumber);

  row("Reference", reference);

  row("Session ID", session);

  row("Date", date);

row("Time", time);

  row("Status","Successful");

  y+=10;

  doc.setDrawColor(220);
  doc.line(20,y,190,y);

  y+=15;

  doc.setFontSize(10);

  doc.text(
      "This receipt was generated by Receiptly.",
      20,
      y
  );

  y+=8;

  doc.setFillColor(245,245,245);

doc.roundedRect(
20,
y,
170,
28,
3,
3,
"F"
);

doc.setFontSize(11);

doc.setFont("helvetica","bold");

doc.text(
"Receiptly",
center,
y+10,
{
align:"center"
}
);

doc.setFontSize(9);

doc.setFont("helvetica","normal");

doc.text(
"This receipt is computer generated.",
center,
y+18,
{
align:"center"
}
);

  doc.save(`${receiptNumber}.pdf`);
}